### ISSUE TITLE
Scripture reference tags

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#30]
> The scripture reference tag should not appear on the site, just in the background. 

...

> The scripture reference tag appears - in the list of songbooks, which is odd. 
> I suspect you may have thought I was asking you to remove the actual scripture reference, and that's why it's gone missing? So maybe you did do the task, but I wasn't clear enough in my instructions.

**Comment by claudinec** [comment]
Scripture references in songs are for Natalie's use. Don't display them on lectionary date page

Display scripture references for lectionary sections.

**Comment by claudinec** [comment]
There may be a redundant scripture field.

**Comment by claudinec** [comment]
Make the scripture reference the section title, as in Blogger.

**Comment by LectionarySinger** [comment]
I think this is OK...?
