### ISSUE TITLE
Display resources in four columns

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#34]
> Is is possible to make the columns list of resources 4 columns wide rather than three. It gets crazily long for some of the more popular titles with only 3 columns.

**Comment by claudinec** [comment]
Here's a good exmaple: http://singingfromthelectionary.org/lectionary/songs-hymns-music-proper-19c-ordinary-24c-pentecost-16

**Comment by claudinec** [comment]
The issue seems to be with songbook links.

**Comment by LectionarySinger** [comment]
This is working, but the columns are too narrow. For some of the song references (e.g. GC(II)405 or any of the 82Hml-XXX refs, they "spill over" into the next line, which makes it hard to read. There is enough room for that block to reach further to the left, so could the columns simply be made wider?

**Comment by claudinec** [comment]
I'm not sure we can achieve exactly what you want. There are two models for arranging blocks or columns of text on the page: "fluid" and "fixed". We're using the fixed model which means that there is a fixed width for each column (relative to the browser window). The fluid model allows these columns to adjust themselves to fit longer words, but I had to change to fixed to accommodate issue #27.

**Comment by LectionarySinger** [comment]
Hmm... the site is looking great with the change in text size. I am having
massive internet problems tonight, so can't edit anything (everything is S
L O W......), but I can look and it looks great.
I think we can live with it as it is. I notice that the colour changes
within the block when you hover the mouse over it, so I don't think it's
too confusing.
should be fine.
N
