### ISSUE TITLE
Order of author and first line/title

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#45]
> I think something has changed! The author of the song is appearing before the First Line. It looks really strange like that. Could you make it so the author appears after the song title?

**Comment by claudinec** [comment]
Song display settings haven't changed, so why ist htis happening?

**Comment by claudinec** [comment]
Try the patch at https://www.drupal.org/node/2320879

**Comment by LectionarySinger** [comment]
Looks good!
