### ISSUE TITLE
Non-scripture based headings for lectionary dates

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#46]
> I'm inserting the Ash Wednesday page, and I noticed that I sometimes have subheadings that are not necessarily associated with a particular reading (e.g. "General Ash Wednesday songs"). Could you make that one of the possibilities in the headings?

**Comment by claudinec** [comment]
The General section (at the top of the section menu) already exists for this purpose.

**Comment by LectionarySinger** [comment]
A-ha! Great.

**Comment by LectionarySinger** [comment]
Except that if I use that feature, then click on the heading in the updated website, it goes to a search for "General Ash Wednesday Songs" in oremus! Not sure how to fix that!

**Comment by claudinec** [comment]
Why not just leave the scripture references blank? And move that section to the top?
