### ISSUE TITLE
Private song notes are not private

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#47]
> The "private comments" are coming up on the website (that is, they're not being private)...

**Comment by claudinec** [comment]
Example: http://singingfromthelectionary.org/song/cup-we-bless

**Comment by claudinec** [comment]
Content Access is disabled!

**Comment by claudinec** [comment]
No, we're using Field Permissions.

**Comment by LectionarySinger** [comment]
Looks good.
